// Rewrite the instructions in your own words

// Write the objectives and the tests
AFK, LOL, ASAP, BTW are examples of acronyms.

*Away From Keyboard*

*Laughing Out Loud*

*As Soon As Possible*

*By The Way*


// Write the pseudocode

variable for result 
variable for acronyms to prompt for text 
variable for acronyms to title case
variable to make the list item from text with space 
for each item in the list to result open the text in the item 
with the first letter
print result 


// paste your JS generated by blockly below here
result, acron, item;

function textToTitleCase(str) {
  return str.replace(/\S+/g,
      function(txt) {return txt[0].toUpperCase() + txt.substring(1).toLowerCase();});
}


result = '';
acron = window.prompt('enter your text');
acron = textToTitleCase(acron);
acron = acron.split(' ');
for (var item_index in acron) {
  item = acron[item_index];
  result += String(item.charAt(0));
}
window.alert(result);